### ISSUE TITLE
OM-D E-M10 II Support?

### ISSUE THREAD

**Issue by HelgenX** [mauriciojost/olympus-photosync#109]
I'd love to use your software, but it seems that it isn't compatible with the E-M10 Mark II. I connect to the wifi on either my laptop or desktop of the camera, and unfortunately, everything stops there. I can't go any further, your software; but others software cannot pick up the IP address of the camera.

**Comment by mauriciojost** [comment]
Hello HelgenX,
Thanks for reaching out!
So you complete totally step 4 and then when executing step 5 the app does not work? Or something else? I would need more details to help you, like until where in the steps in the README you've successfully arrived, and when there is an issue what message/error you see exactly.
Aso I'd appreciate if you tell me which version of the app you are using.
I'd expect the app to work with your camera because both the older and the newer version of the EM10 do work with it (checked by myself and Alex respectively). 
Cheers,
Mauricio

**Comment by HelgenX** [comment]
Sorry for the late response. I did end up getting it to work in the end. It had nothing to do with your software, just wasn't sure why it wasn't connecting. But your software did work when I got it to connect, thank you!

**Comment by mauriciojost** [comment]
Glad to hear that. Given the confirmation I will add the camera to the list of supported ones. Thanks!

**Comment by mauriciojost** [comment]
Also if you liked the project @helhenx please give it a star. Knowing that people took the time to do it sort of motivates me to keep maintaining the project. :blush:
